# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.DateField(default=datetime.date.today, verbose_name='Effective through ')),
            ],
        ),
    ]
